import assert from 'node:assert/strict';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { defaultConfig, saveConfig } from 'common-memory-core';
const root = process.cwd(), home = join(root, 'automatic-home');
process.env.COMMON_MEMORY_HOME = home;
const packageRoot = new URL('../', import.meta.resolve('common-memory-core'));
const { installIntegrations, removeIntegrations, readInstallationState } = await import(new URL('dist/cli/integrations.js', packageRoot));
const config = defaultConfig(); config.remote.model = 'synthetic'; saveConfig(config);
const pi = { id: 'pi', name: 'Pi', root: join(root, 'automatic-pi'), mode: 'posix', hooks: true };
const codex = { id: 'codex', name: 'Codex CLI', root: join(root, 'automatic-codex'), mode: 'posix', hooks: false };
mkdirSync(pi.root); writeFileSync(join(pi.root, 'settings.json'), '{"theme":"preserved"}\n');
installIntegrations([pi, codex], config.dataRoot);
const settings = JSON.parse(readFileSync(join(pi.root, 'settings.json'), 'utf8'));
const extension = await import(pathToFileURL(settings.extensions[0]));
const events = [], tools = [], commands = [];
await extension.default({ on: name => events.push(name), registerTool: tool => tools.push(tool.name), registerCommand: name => commands.push(name) });
assert.ok(events.includes('before_agent_start')); assert.ok(events.includes('message_end')); assert.ok(tools.includes('memory_read')); assert.ok(commands.includes('memory-refresh'));
assert.match(readFileSync(join(codex.root, 'config.toml'), 'utf8'), /memory_read/);
assert.equal(readInstallationState().targets.length, 2);
removeIntegrations(['pi', 'codex']);
assert.deepEqual(JSON.parse(readFileSync(join(pi.root, 'settings.json'), 'utf8')), { theme: 'preserved' });
assert.equal(existsSync(settings.extensions[0]), false); assert.equal(existsSync(join(config.dataRoot, 'runtime.sqlite')), false);
console.log('Packaged automatic integration installation, actual Pi wrapper registration and ownership-safe removal passed.');
