import { afterEach,expect,it,vi } from 'vitest';
import { mkdirSync,mkdtempSync,rmSync,writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { defaultConfig } from '../../src/config/config.js';
import { codexHook,refreshSession } from '../../src/cli/codex-hook.js';
import { RuntimeStore } from '../../src/v2/runtime.js';
import { startTestService } from '../helpers/service-daemon.js';
import { retryJob } from '../../src/cli/operations.js';
import { ServiceClient } from '../../src/service/client.js';
import { ProjectRegistry } from '../../src/v2/registry.js';
const cleanup:(()=>unknown|Promise<unknown>)[]=[];afterEach(async()=>{for(const fn of cleanup.splice(0).reverse())await fn();vi.unstubAllEnvs();});
it('two explicit retries each execute against the then-current durable state',async()=>{const home=mkdtempSync(join(tmpdir(),'cm-retry-actions-'));cleanup.push(()=>rmSync(home,{recursive:true,force:true}));const config=defaultConfig({COMMON_MEMORY_HOME:home});vi.stubEnv('COMMON_MEMORY_HOME',home);config.remote.model='synthetic';writeFileSync(join(home,'config.json'),JSON.stringify(config));let store=new RuntimeStore(config.dataRoot);store.enqueue({sessionId:'target',entryId:'e',scope:'global',source:'interactive',text:'target',observedAt:new Date().toISOString()});const target=store.claim({force:true})!;store.db.prepare("UPDATE jobs SET state='dead' WHERE id=?").run(target.id);store.db.prepare("UPDATE observations SET state='dead' WHERE jobId=?").run(target.id);store.enqueue({sessionId:'blocker',entryId:'e',scope:'global',source:'interactive',text:'blocker',observedAt:new Date().toISOString()});const blocker=store.claim({force:true})!;expect(blocker.id).not.toBe(target.id);store.close();const stop=await startTestService(home);cleanup.push(stop);await retryJob(config,target.id);store=new RuntimeStore(config.dataRoot);expect(store.db.prepare('SELECT state FROM jobs WHERE id=?').get(target.id)!.state).toBe('retry');store.db.prepare("UPDATE jobs SET state='dead' WHERE id=?").run(target.id);store.db.prepare("UPDATE observations SET state='dead' WHERE jobId=?").run(target.id);store.close();await retryJob(config,target.id);store=new RuntimeStore(config.dataRoot);try{expect(store.db.prepare('SELECT state FROM jobs WHERE id=?').get(target.id)!.state).toBe('retry');expect(store.db.prepare("SELECT COUNT(*) AS n FROM service_requests WHERE result LIKE '%queued%'").get()!.n).toBe(2);}finally{store.close();}});

it('journal replay fails closed when current snapshot authorization is revoked',async()=>{const home=mkdtempSync(join(tmpdir(),'cm-snapshot-revoke-'));cleanup.push(()=>rmSync(home,{recursive:true,force:true}));const config=defaultConfig({COMMON_MEMORY_HOME:home});config.remote.model='synthetic';const projectRoot=join(home,'project');mkdirSync(projectRoot);const project=new ProjectRegistry(config.dataRoot).register(projectRoot,'Project'),scope=`project:${project.id}`;config.disclosure.allowedScopes=['global',scope];config.writableScopes=['global',scope];writeFileSync(join(home,'config.json'),JSON.stringify(config));mkdirSync(join(config.dataRoot,'memory/projects'),{recursive:true});writeFileSync(join(config.dataRoot,'memory/projects',`${project.id}.md`),'# Project\n\n## Private\nREVOKED_BODY');const transcript=join(home,'rollout.jsonl');writeFileSync(transcript,JSON.stringify({type:'session_meta',payload:{cli_version:'0.154.0'}})+'\n');const channel={kind:'hook' as const,client:'codex' as const,instance:'host'},stop=await startTestService(home,[channel]);cleanup.push(stop);const client=new ServiceClient(channel,home),payload={event:{hook_event_name:'SessionStart',source:'startup',session_id:'s',turn_id:'t',cwd:projectRoot,transcript_path:transcript}};const first=await client.call('hook.event',payload,{requestId:'same-start',wake:false});expect(JSON.stringify(first)).toContain('REVOKED_BODY');config.disclosure.allowedScopes=['global'];config.writableScopes=['global'];writeFileSync(join(home,'config.json'),JSON.stringify(config));const replay=await client.call('hook.event',payload,{requestId:'same-start',wake:false});expect(JSON.stringify(replay)).not.toContain('REVOKED_BODY');});

it('two explicit refresh actions each replace snapshot state and use independent journal identities',async()=>{const home=mkdtempSync(join(tmpdir(),'cm-refresh-actions-'));cleanup.push(()=>rmSync(home,{recursive:true,force:true}));const config=defaultConfig({COMMON_MEMORY_HOME:home});config.remote.model='synthetic';writeFileSync(join(home,'config.json'),JSON.stringify(config));const memory=join(config.dataRoot,'memory/profile.md');mkdirSync(join(config.dataRoot,'memory'),{recursive:true});writeFileSync(memory,'# Profile\n\n## Synthetic\nA');const transcript=join(home,'rollout.jsonl');writeFileSync(transcript,JSON.stringify({type:'session_meta',payload:{cli_version:'0.154.0'}})+'\n');const channel={kind:'hook' as const,client:'codex' as const,instance:'host'},stop=await startTestService(home,[channel]);cleanup.push(stop);const event=(name:string,source='startup')=>JSON.stringify({hook_event_name:name,source,session_id:'s',turn_id:'t',cwd:home,transcript_path:transcript});expect(JSON.stringify(await codexHook(event('SessionStart'),home,'host'))).toContain('A');writeFileSync(memory,'# Profile\n\n## Synthetic\nB');await refreshSession(home,'codex','host','s');expect(JSON.stringify(await codexHook(event('PostToolUse'),home,'host'))).toContain('B');writeFileSync(memory,'# Profile\n\n## Synthetic\nC');await refreshSession(home,'codex','host','s');expect(JSON.stringify(await codexHook(event('PostToolUse'),home,'host'))).toContain('C');const store=new RuntimeStore(config.dataRoot);try{expect(store.db.prepare("SELECT COUNT(*) AS n FROM service_requests WHERE result LIKE '%refreshed%'").get()!.n).toBe(2);}finally{store.close();}});
