import { isAbsolute, resolve } from 'node:path';
import type { CommonMemoryConfig } from '../config/config.js';
import { DOCUMENT_AUTHORS, prepareDocumentImport, type DocumentAuthor, type DocumentImportOutcome } from '../v2/document-import.js';
import { ProjectRegistry } from '../v2/registry.js';
import { ServiceClient } from '../service/client.js';
import { setTimeout as delay } from 'node:timers/promises';

export interface ImportOptions {file:string;workspace?:string;author?:DocumentAuthor;label?:string;wait:boolean}
export function parseImportArgs(args:string[]):ImportOptions{const options:ImportOptions={file:'',wait:true};for(let i=0;i<args.length;i++){const arg=args[i]!;if(arg==='--no-wait')options.wait=false;else if(arg==='--workspace'||arg==='--author'||arg==='--label'){const value=args[++i];if(value===undefined||value.startsWith('--'))throw new TypeError(`${arg} requires a value`);if(arg==='--workspace'){if(!isAbsolute(value))throw new TypeError('--workspace must be an absolute path');options.workspace=value;}else if(arg==='--author'){if(!DOCUMENT_AUTHORS.includes(value as DocumentAuthor))throw new TypeError(`--author must be one of ${DOCUMENT_AUTHORS.join('|')}`);options.author=value as DocumentAuthor;}else options.label=value;}else if(arg.startsWith('--'))throw new TypeError(`Unknown import option ${arg}`);else if(options.file)throw new TypeError('import accepts exactly one file');else options.file=arg;}if(!options.file)throw new TypeError('import requires a Markdown file path');return options;}

/** Preflight is local and model-free; durable admission and status are service-owned. */
export async function runImport(config:CommonMemoryConfig,args:string[],log:(line:string)=>void=console.log):Promise<{exitCode:number;outcome:DocumentImportOutcome|null}>{
  const options=parseImportArgs(args);if(!config.disclosure.allowedProvenance.includes('document_import'))throw new Error('IMPORT_DISABLED: allow "Imported Markdown documents" in common-memory config (disclosure.allowedProvenance: document_import)');let contextId='global';if(options.workspace){let project;try{project=new ProjectRegistry(config.dataRoot).resolve(options.workspace);}catch{}if(!project)throw new Error('UNREGISTERED_WORKSPACE: register it with common-memory project register');contextId=`project:${project.id}`;}if(!config.disclosure.allowedScopes.includes(contextId))throw new Error(`CONTEXT_UNAVAILABLE: ${contextId} is not in disclosure.allowedScopes`);
  const prepared=prepareDocumentImport(options.file,{label:options.label,author:options.author,maxTotalBytes:config.disclosure.maxTotalBytes,limits:config.disclosure});log(`file: ${prepared.fileName} (${prepared.bytes} bytes, ${prepared.chunks.length} parts); label: ${prepared.sourceLabel}; declared author: ${prepared.declaredAuthor}; context: ${contextId}`);const client=new ServiceClient({kind:'cli'}),payload={file:resolve(options.file),...(options.workspace?{workspace:options.workspace}:{}),...(options.author?{author:options.author}:{}),...(options.label?{label:options.label}:{}),contentDigest:prepared.contentDigest};
  const admissionOptions={requestId:`document-${prepared.contentDigest}`};let admitted:{importId:string;duplicate:boolean;parts:number};try{admitted=await client.call('document.import',payload,admissionOptions);}catch(error){if(!(error instanceof Error)||error.message!=='DELIVERY_UNCERTAIN')throw error;try{admitted=await client.call('document.import',payload,admissionOptions);}catch(second){throw new Error(`导入 ${prepared.importId} 的投递状态不确定；请保留此 ID 查询，不要更换 ID。`,{cause:second});}}log(admitted.duplicate?`duplicate: ${admitted.importId}`:`accepted: queued as ${admitted.importId} (${admitted.parts} ${admitted.parts===1?'part':'parts'}); accepted means durably queued, not remembered`);if(!options.wait){const outcome=await client.call<DocumentImportOutcome>('document.status',{importId:admitted.importId,contextId,count:admitted.parts},{wake:false});return {exitCode:0,outcome};}
  for(;;){const outcome=await client.call<DocumentImportOutcome>('document.status',{importId:admitted.importId,contextId,count:admitted.parts},{wake:false});if(outcome.complete||outcome.parts.some(part=>['dead','paused','quarantined'].includes(part.state))){log(outcome.complete?`complete: retained in ${outcome.retainedIn.join(', ')||'no current destination'}`:'incomplete: inspect processing status');log(JSON.stringify(outcome,null,2));return {exitCode:outcome.complete?0:1,outcome};}await delay(250);}
}
