import { afterEach, expect, it } from "vitest";
import { rmSync } from "node:fs";
import { join } from "node:path";
import { CoreService } from "../../src/core/service/core-service.js";
import { TestClock, TestIds, authority, contributor, evidence, suggested, tempRoot } from "../helpers.js";
import { conservativeTokenUpperBound } from "../../src/core/context/budget.js";
let cleanup: () => void = () => undefined; afterEach(() => cleanup());
it("preserves all core boundaries or fails with CORE_BUDGET_EXCEEDED", () => {
  const root = tempRoot(); cleanup = root.cleanup; const service = new CoreService({ dataRoot: root.path, clock: new TestClock(), ids: new TestIds() }); service.initialize();
  const p = service.propose({ operation: "add_fact", target_fact_ids: [], suggested_fact: { ...suggested, kind: "constraint", statement: "操作陌生系统前必须先解释数据流" }, evidence, reasoning: "用户边界", confidence: "high" }, contributor); if (!p.ok) throw new Error(); service.approve({ proposal_id: p.data.proposal_id, expected_store_revision: p.store_revision!, note: null }, authority);
  rmSync(join(root.path, "index", "memory.sqlite"), { force: true }); const pack = service.contextPack({ task: "数据流", scopes: ["global"], max_tokens: 5000 }); expect(pack.ok).toBe(true); if (pack.ok) { expect(pack.data.boundaries).toHaveLength(1); expect(pack.data.boundaries[0]?.source).toMatchObject({ type: "user_statement", source_client: "local_user", reference: "message-1" }); }
  const summary = service.summary({ scopes: ["global"] }); if (!summary.ok) throw new Error(); expect(summary.data.generated_at).toBe("2026-01-01T00:00:00.000Z");
  const tooSmall = service.contextPack({ task: "数据流", scopes: ["global"], max_tokens: 1 }); expect(!tooSmall.ok && tooSmall.error.details.reason).toBe("CORE_BUDGET_EXCEEDED");
});
it("maps invalid valid_at consistently to VALIDATION_FAILED", () => { const root = tempRoot(); cleanup = root.cleanup; const service = new CoreService({ dataRoot: root.path, clock: new TestClock(), ids: new TestIds() }); service.initialize(); for (const response of [service.get({ scopes: ["global"], valid_at: "not-a-time" }), service.summary({ scopes: ["global"], valid_at: "not-a-time" }), service.search({ query: "中文", scopes: ["global"], valid_at: "not-a-time" }), service.contextPack({ task: "中文", scopes: ["global"], valid_at: "not-a-time", max_tokens: 1000 })]) expect(!response.ok && response.error.code).toBe("VALIDATION_FAILED"); });
it("degrades context without partial results when index publish fails", () => { const root = tempRoot(); cleanup = root.cleanup; const service = new CoreService({ dataRoot: root.path, clock: new TestClock(), ids: new TestIds(), faults: { checkpoint(point) { if (point === "index-publish") throw new Error("publish failure"); } } }); service.initialize(); const proposal = service.propose({ operation: "add_fact", target_fact_ids: [], suggested_fact: { ...suggested, kind: "constraint", statement: "修改系统前先展示计划" }, evidence, reasoning: "boundary", confidence: "high" }, contributor); if (!proposal.ok) throw new Error(); service.approve({ proposal_id: proposal.data.proposal_id, expected_store_revision: proposal.store_revision!, note: null }, authority); const search = service.search({ query: "系统计划", scopes: ["global"] }); expect(!search.ok && search.error.code).toBe("INDEX_OUTDATED"); const pack = service.contextPack({ task: "系统计划", scopes: ["global"], max_tokens: 5000 }); expect(pack.ok).toBe(true); if (pack.ok) { expect(pack.data.degraded).toBe(true); expect(pack.data.warnings).toEqual(["INDEX_OUTDATED"]); expect(pack.data.boundaries).toHaveLength(1); expect(pack.data.relevant).toEqual([]); expect(pack.data.historical).toEqual([]); } });
it("retrieves relevant confirmed archive events into explicit history only", () => { const root = tempRoot(); cleanup = root.cleanup; const clock = new TestClock(); const service = new CoreService({ dataRoot: root.path, clock, ids: new TestIds() }); service.initialize(); const proposal = service.propose({ operation: "add_fact", target_fact_ids: [], suggested_fact: { ...suggested, statement: "Windows 网络故障已在设备上修复", kind: "event", priority: "archive" }, evidence, reasoning: "历史事件", confidence: "high" }, contributor); if (!proposal.ok) throw new Error(); service.approve({ proposal_id: proposal.data.proposal_id, expected_store_revision: proposal.store_revision!, note: null }, authority); const pack = service.contextPack({ task: "Windows 网络", scopes: ["global"], include_history: true, time_range: { from: "2025-12-01T00:00:00.000Z", to: "2026-02-01T00:00:00.000Z" }, max_tokens: 5000 }); expect(pack.ok).toBe(true); if (pack.ok) { expect(pack.data.relevant).toHaveLength(0); expect(pack.data.historical.some((entry) => entry.statement.includes("Windows"))).toBe(true); } });
it("freezes model-independent conservative bounds for Chinese and English", () => { const english = conservativeTokenUpperBound({ statement: "change plan" }); const chinese = conservativeTokenUpperBound({ statement: "修改计划" }); expect(english).toBeGreaterThan(96); expect(chinese).toBeGreaterThan(96); expect(conservativeTokenUpperBound({ statement: "修改计划" })).toBe(chinese); });
