import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
const root = fileURLToPath(new URL("../", import.meta.url)); const temp = mkdtempSync(join(tmpdir(), "common-memory-consumer-"));
try {
  mkdirSync(join(temp, "node_modules")); symlinkSync(root, join(temp, "node_modules", "common-memory-core"), process.platform === "win32" ? "junction" : "dir");
  writeFileSync(join(temp, "package.json"), JSON.stringify({ type: "module" }));
  writeFileSync(join(temp, "consumer.ts"), `import { CoreService, RecallOrchestrator, RemoteRecallPlanner, MemoryManager, OpenAIResponsesMemoryModel, createConfiguredMemoryModel, loadConfig, createLocalUserMemoryControl, MemoryManagerJobStore, MemoryManagerScheduler, type CommonMemoryConfig, type GetInput, type RecallRequest, type RecallResult, type RemoteDisclosurePolicy, type ObservationSourcePort, type MemoryModelPort, type GovernanceLogPage, type UndoPreviewDto } from "common-memory-core";\nconst input: GetInput = { scopes: ["global"] }; const recallInput: RecallRequest = { query: "偏好", scopes: ["global"], max_context_bytes: 12000 }; const recallResult: RecallResult | undefined = undefined; const policy: RemoteDisclosurePolicy | undefined = undefined; const ports: [ObservationSourcePort?, MemoryModelPort?] = []; const values: [GovernanceLogPage?, UndoPreviewDto?] = []; const config: CommonMemoryConfig | null = loadConfig(); void input; void recallInput; void recallResult; void policy; void ports; void values; void config; void CoreService; void RecallOrchestrator; void RemoteRecallPlanner; void MemoryManager; void OpenAIResponsesMemoryModel; void createConfiguredMemoryModel; void createLocalUserMemoryControl; void MemoryManagerJobStore; void MemoryManagerScheduler;\n`);
  writeFileSync(join(temp, "tsconfig.json"), JSON.stringify({ compilerOptions: { strict: true, module: "NodeNext", moduleResolution: "NodeNext", target: "ES2024", skipLibCheck: true }, include: ["consumer.ts"] }));
  execFileSync(join(root, "node_modules", ".bin", process.platform === "win32" ? "tsc.cmd" : "tsc"), ["-p", join(temp, "tsconfig.json"), "--noEmit"], { stdio: "inherit" });
  writeFileSync(join(temp, "runtime.mjs"), `import { createHash } from "node:crypto"; import { CoreService, MemoryManager, OpenAIResponsesMemoryModel, createLocalUserMemoryControl } from "common-memory-core"; const core = new CoreService({ dataRoot: process.env.DATA_ROOT }); const initialized = core.initialize(); if (!initialized.ok) throw new Error(initialized.error.code); const text = "用户默认使用中文交流"; const fetchImpl = async (url, init) => { if (url !== "https://compatible.example.test/gateway/v1/responses") throw new Error("endpoint"); const body = JSON.parse(init.body); if (body.store !== false || String(init.headers.authorization).includes("consumer-key") === false || JSON.stringify(body).includes("consumer-key")) throw new Error("remote contract"); const projection = JSON.parse(body.input[1].content[0].text); const analysis = { contract_version: "memory_analysis_v1", request_id: projection.request_id, based_on_knowledge_revision: projection.based_on_knowledge_revision, based_on_store_revision: projection.based_on_store_revision, actions: [{ action: "add", confidence: "high", statement: text, kind: "preference", scope: "global", priority: "normal", target_fact_ids: [], evidence_refs: ["ev_1"], tags: ["communication"], expires_at: null, reason: "用户明确陈述" }], abstained_reason_codes: [] }; return new Response(JSON.stringify({ status: "completed", incomplete_details: null, error: null, output: [{ type: "message", status: "completed", role: "assistant", content: [{ type: "output_text", text: JSON.stringify(analysis), annotations: [] }] }], usage: { input_tokens: 1, output_tokens: 1, total_tokens: 2 } }), { status: 200 }); }; const disclosurePolicy = { enabled: true, allowedScopes: ["global"], allowedProvenance: ["user_statement"], maxExcerptBytes: 1000, maxCandidateBytes: 1000, maxTotalBytes: 64000 }; const model = new OpenAIResponsesMemoryModel({ apiKey: "consumer-key", model: "consumer-model", baseUrl: "https://compatible.example.test/gateway/v1", disclosurePolicy, fetch: fetchImpl }); const manager = new MemoryManager({ core, model, observations: { resolve: async ref => ({ ...ref, text, observedAt: "2026-01-01T00:00:00.000Z", sessionId: "consumer", reference: "turn-1" }) }, disclosurePolicy }); const digest = "sha256:" + createHash("sha256").update(text).digest("hex"); const run = await manager.extract({ observations: [{ observationId: "o1", digest, scope: "global", provenance: "user_statement" }] }); if (run.outcome !== "committed") throw new Error("extract failed:" + run.outcome); const log = core.listGovernance(); if (!log.ok || log.data.items.length !== 1 || !log.data.items[0].review) throw new Error("governance log failed"); const local = createLocalUserMemoryControl(core, { sessionId: "consumer" }); const preview = local.previewUndo([log.data.items[0].review.id]); if (!preview.ok) throw new Error("preview failed"); const undone = local.applyUndo(preview.data); if (!undone.ok) throw new Error("undo failed:" + undone.error.code);`);
  execFileSync(process.execPath, [join(temp, "runtime.mjs")], { env: { ...process.env, DATA_ROOT: join(temp, "data") }, stdio: "inherit" });
  console.log("external package-root consumer remote/governance/undo smoke passed");
} finally { rmSync(temp, { recursive: true, force: true }); }
