import { afterEach, expect, it } from "vitest";
import { CoreService } from "../../src/core/service/core-service.js";
import { projectOperation } from "../../src/core/governance/project-review.js";
import type { Proposal } from "../../src/core/contracts/types.js";
import { TestClock, TestIds, authority, contributor, evidence, suggested, tempRoot } from "../helpers.js";
let cleanup: () => void = () => undefined; afterEach(() => cleanup());
function propose(service: CoreService, input: Parameters<CoreService["propose"]>[0]) { const result = service.propose(input, contributor); expect(result.ok).toBe(true); if (!result.ok) throw new Error(); return result; }
it("rejects operation-inapplicable edit keys before projection", () => { const base = { schema_version: 1 as const, id: "proposal.99999999", target_fact_ids: [], evidence, reasoning: "x", confidence: "high" as const, source: { client: "local_user" as const, received_at: "2026-01-01T00:00:00.000Z" }, created_at: "2026-01-01T00:00:00.000Z" }; const add = { ...base, operation: "add_fact" as const, target_fact_ids: [] as [], suggested_fact: suggested } satisfies Proposal; const expire = { ...base, operation: "expire_fact" as const, target_fact_ids: ["fact.99999999"], suggested_expiration: { expires_at: "2026-01-01T00:00:00.000Z", reason: "x" } } satisfies Proposal; expect(() => projectOperation(add, { reason: "ignored" } as never)).toThrow(); expect(() => projectOperation(expire, { statement: "ignored" } as never)).toThrow(); });
it("executes add, edit-and-supersede, and expire without a delete path", () => {
  const root = tempRoot(); cleanup = root.cleanup; const clock = new TestClock(); const service = new CoreService({ dataRoot: root.path, clock, ids: new TestIds() }); service.initialize();
  const add = propose(service, { operation: "add_fact", target_fact_ids: [], suggested_fact: suggested, evidence, reasoning: "长期偏好", confidence: "high" }); const a = service.approve({ proposal_id: add.data.proposal_id, expected_store_revision: add.store_revision!, note: null }, authority); expect(a.ok).toBe(true);
  const current = service.get({ scopes: ["global"] }); if (!current.ok) throw new Error(); const oldId = current.data.facts[0]!.id;
  clock.value = "2026-01-02T00:00:00.000Z";
  const supersede = propose(service, { operation: "supersede_fact", target_fact_ids: [oldId], suggested_fact: { ...suggested, statement: "用户偏好中文，但技术术语保留英文" }, evidence: { ...evidence, provenance_type: "user_correction", observed_at: clock.value }, reasoning: "用户修正", confidence: "high" });
  const s = service.editApprove({ proposal_id: supersede.data.proposal_id, expected_store_revision: supersede.store_revision!, note: "调整表述", edits: { statement: "用户默认使用中文，技术术语保留英文" } }, authority); expect(s.ok).toBe(true);
  const now = service.get({ scopes: ["global"] }); if (!now.ok) throw new Error(); expect(now.data.facts).toHaveLength(1); const newId = now.data.facts[0]!.id; expect(now.data.facts[0]!.statement).toContain("技术术语");
  clock.value = "2026-01-03T00:00:00.000Z"; const expire = propose(service, { operation: "expire_fact", target_fact_ids: [newId], suggested_expiration: { expires_at: clock.value, reason: "用户确认偏好不再适用" }, evidence: { ...evidence, provenance_type: "user_correction", observed_at: clock.value }, reasoning: "用户明确撤回", confidence: "high" }); const x = service.approve({ proposal_id: expire.data.proposal_id, expected_store_revision: expire.store_revision!, note: null }, authority); if (!x.ok) throw new Error(JSON.stringify(x.error));
  const none = service.get({ scopes: ["global"] }); expect(none.ok && none.data.facts).toHaveLength(0); const history = service.get({ scopes: ["global"], include_history: true }); if (!history.ok) throw new Error(); expect(history.data.facts.map((fact) => fact.status).sort()).toEqual(["expired", "superseded"]); expect(history.data.facts.some((fact) => fact.status === "deleted")).toBe(false);
});
